### PR TITLE
Pre-release activities (prepare for CRAN release)

### LINKED ISSUE #172: Pre-release activities
### Summary

Please carry out these tasks in preparation for the teal modules CRAN release:

* Review and update:
    * README.md (check example code)
    * NEWS.md
* Run urlchecker::url_check() to identify broken links and fix
* Review functions:
    * @example tag, make sure it runs, fix if otherwise
    * Make sure functions has @return tag to document the return value
    * no \dontrun tag, replace with if(interactive()) if needed
* Sanity check of all vignettes, make sure there is no typo, no wrong format, etc.
* Run R CMD check --as-cran make sure everything pass
* Package `Title` is not duplicated in Package `Description` in DESCRIPTION file (e.g. this happens in teal.slice currently)
* All package names in `Title` and `Description` fields of DESCRIPTION file are quoted with `'`
* You have checked the Package Release Template https://github.com/insightsengineering/teal.reporter/pull/205/files
* Make sure there are no `:::` in examples
    * if you need to retain the example that uses `:::`, use `getFromNamespace()` function.
* Make sure all `teal.*` mentions are lower-cased and quoted
* Make Sure inst/WORDLIST is minimalized
* Make sure non-exported functions do not have examples
* Make sure each link to our documentation hosted with pkgdown on github pages do not have `/main/` in the address but it has `/latest/` instead, so we always expose the documentation of the latest release and not what's currently on main branch but not yet released

\*new\*:
* Remove old rd syntax
* Switch from title case into sentence case for title and descriotion of functions.

### PR DESCRIPTION
**Pull request by averissimo**
# Pull Request

Fixes #172 

### Summary

* Review and update:
    * [x] README.md (check example code)
    * [x] NEWS.md
      * one liner change
* Review functions:
    * [x] @example tag, make sure it runs, fix if otherwise
    * [x] Make sure functions has @return tag to document the return value
    * [x] no \dontrun tag, replace with if(interactive()) if needed
      * `merge_datasets` example is insufficient
* [x] Package `Title` is not duplicated in Package `Description` in DESCRIPTION file (e.g. this happens in teal.slice currently)
* [x] You have checked the Package Release Template https://github.com/insightsengineering/teal.reporter/pull/205/files
* [x] Make sure there are no `:::` in examples
    * if you need to retain the example that uses `:::`, use `getFromNamespace()` function.
* [x] remove package:: call and depend package:: call from example. @kartikeyakirar 
* [x] Make sure all `teal.*` mentions are lower-cased and quoted
* [x] Make sure each link to our documentation hosted with pkgdown on github pages do not have `/main/` in the address
  * it should have has `/latest-tag/` instead
  * so we always expose the documentation of the latest release and not what's currently on main branch but not yet released
* [x] Remove old rd syntax
* [x] Switch from title case into sentence case for title and description of functions.
* [x] All package names in `Title` and `Description` fields of DESCRIPTION file are quoted with `'` _(not backtick)_
* [x] Sanity check of all vignettes, make sure there is no typo, no wrong format, etc. @kartikeyakirar 

#### New

* [x] Remove prefixes from data calls `rADRS`, `rADTTE`, etc... (just like `{teal.data}`)
* [x] Remove `return` wrapper if it is the last expression (per NEST guidelines)
  * #177
* [x] Remove  exception in `.lintr`: `indentation_linter = NULL` 
* [x]  ~Test for unused functions (in package and overall in NEST)~ @averissimo
    * PR request against this feature branch 
    * 🛑 This should not be done on this release as it may have unintended consequences.
       * [See this comment](https://github.com/insightsengineering/teal.transform/pull/176#issuecomment-1935996312) with possible candidates
 * [x] Standard order of roxygen2 tags 
   * `@title ➡️ @doctype ➡️ @description ➡️ @details ➡️ @rdname ➡️ `
   * `➡️ @inheritParams ➡️ @params ➡️ @return ➡️ @seealso ➡️ @references ➡️`
   * `➡️ @examples ➡️ @export ➡️ @keywords  ➡️  @noRd`
* [x] Remove `@noMd` (in favor of `Roxygen: list(markdown = TRUE)` in `DESCRIPTION`)

#### To consider?
* [x] Convert "# nolint" to specific rule exception
  * https://github.com/insightsengineering/teal.transform/pull/178
* [x] ~Added `resolve()` to the list of exported functions as the sub-functions are exported (`resolve.delayed_variable_choices`, ...).~
  * Let's discuss if this needs to be reverted.
  * Edit: this is a trick to have S3methods internally as `resolve` should not be exported see aff0f350

#### Move to its own issue

* [x] Make sure non-exported functions do not have examples
  * https://github.com/insightsengineering/teal.transform/issues/181

#### After checklist is completed _(🚨 blocked until checklist is completed)_
* [x] Run urlchecker::url_check() to identify broken links and fix
* [x] Run R CMD check --as-cran make sure everything pass
* [x] Make Sure `inst/WORDLIST` is minimalized

#### Content review _(🚨 blocked for now)_

All tasks above are mostly focused on structure, standards and cleanup. Here is to look at content

What to look for:

* Review content of titles, descriptions, params, etc.
  * They should be clear to the reader 
* Review vignettes
  * Review content
  * All chunks of code are runnable

Content-related tasks should have a PR against this feature branch.

### CODE REVIEW

File: R/merge_datasets.R [hunk 1]
```diff
@@ -24,20 +43,43 @@
 #' @export
 #'
 #' @examples
-#' \dontrun{
-#' # inside teal module server function
-#' response <- data_extract_srv(
-#'   id = "reponse",
-#'   data_extract_spec = response_spec,
-#'   datasets = datasets
```
Comment (averissimo) [inline R/merge_datasets.R:32]: Moved this up to `@details` section and created a runnable example based on the tests

File: R/call_utils.R [hunk 2]
```diff
@@ -386,23 +424,23 @@ call_extract_list <- function(dataname, varname, dollar = TRUE) {
...
-#' print_call_and_eval <- function(x) {
-#'   eval(print(x))
-#' }
+#' print_call_and_eval <- function(x) eval(print(x))
 #'
 #' print_call_and_eval(
-#'   teal.transform:::call_with_colon("glue::glue", "x = {x}", x = 10)
+#'   call_with_colon("glue::glue", "x = {x}", x = 10)
 #' )
-#' \dontrun{
```
Comment (averissimo) [inline R/call_utils.R:397]: This example seems to run without problems and is fast so I removed the tag #yolo

I want to ask for someone to look at this and the comments and examples before resolving the comment :bow:

**Comment by averissimo** [comment]
@kartikeyakirar Went through all the `R/` files and applied the necessary changes:

* Switch from title case into sentence case for title and description of functions.
* Make sure functions has `@return` tag to document the return value
* Standard order of roxygen2 tags
* Remove `@noMd` (in favor of Roxygen: list(markdown = TRUE) in DESCRIPTION)

Just as we talked, feel free to take one of the unchecked items tomorrow.

I suggest editing the top post and placing your name next to it, so the team knows that you're doing it. This goes to other team members as well :smile:

**Review by averissimo — COMMENTED** [review]
Some notes from iterating on all source files

**Comment by kartikeyakirar** [comment]
> * [x] remove package:: call and depend package:: call from example.

@averissimo I have updated example. and few of them were not working that is also fixed here.[e1ac439](https://github.com/insightsengineering/teal.transform/pull/176/commits/e1ac439da79448080e41232215877134b2ac6663)

**Comment by averissimo** [comment]
Nice @kartikeyakirar ! 

Can you elaborate on what wasn't working, the shiny apps in the examples or a "normal" example?

Asking because I ran the private ones with `library(teal.transform)` as to not import any non-exported functions and ran `devtools::run_examples(fresh = T)`

I'm wondering what I missed :sweat_smile:

**Comment by kartikeyakirar** [comment]
> Can you elaborate on what wasn't working, the shiny apps in the examples or a "normal" example?

it's mostly shiny app examples, cause problem after initialization which were not detected by the` devtools::run_examples(fresh = TRUE)`


The provided text describes issues encountered with Shiny applications, particularly focusing on initialization and reactive data management. Here's a revised version for clarity and conciseness:

This document outlines two specific challenges encountered with Shiny applications during the post-initialization phase, which were not detected by the devtools::run_examples(fresh = TRUE) command:

1.  Case where  issue arises when an application is created using`app <-  shinyApp(...) `and subsequently,` shinyApp(app$ui, app$server) `is invoked for execution. 

2: Reactive Data List Creation: In file  R/merge_expression_module.R, there was a failure to instantiate a reactive data_list. This oversight led to an assertion failure. this is also causes error after app intitialization

File: R/resolve.R [hunk 3]
```diff
@@ -61,8 +62,10 @@
 #'     )
 #'   )
 #'
-#'   teal.transform:::resolve(arm_ref_comp, data_list, keys)
+#'   resolve(arm_ref_comp, data_list, keys)
 #' })
+#' @export
```
[the remark this answers is not in the document]
Comment (averissimo) [reply R/resolve.R]: It needs and it was.

**Comment by averissimo** [comment]
All the original checklist items are done after #178 and #183 are merge

I suggest:
- One of the team members review this PR as it is _(before those 2 are merged)_
- Make the content-based changes in a different PR
  - Cleanup man pages wording
  - Cleanup vignettes _(@vedhav had a good idea on it)_

File: R/utils.R [hunk 4]
```diff
@@ -1,11 +1,15 @@
...
+#' @param sep (`character`) separator to use for splitting.
+#'
+#' @return List of character vectors split by `sep`. Self if `x` is not a `character`.
 #'
-#' @param x (`character`) Character (single)
-#' @param sep (`character`) Separator
 #' @export
+#'
 split_by_sep <- function(x, sep) {
   stopifnot(is.atomic(x))
```
[the remark this answers is not in the document]
Comment (vedhav) [reply R/utils.R:14]: Thanks! This is being addressed in the PR #186

**Comment by kartikeyakirar** [comment]
@averissimo  can you also add 

- add backticks on keyword teal in _pkgdown.yml
- add `PackageCheckArgs: --as-cran` teal.transformer.Rproj

**Comment by averissimo** [comment]
@kartikeyakirar done :heavy_check_mark:

**Comment by m7pr** [comment]
Hey @averissimo and @kartikeyakirar I see you added a new bullet list to the check list

> Remove prefixes from data calls rADRS, rADTTE

So I guess those are changes of changing this `ADSL <- teal.transform::rADSL` to `ADSL <- rADSL`. Unfortunately `rADSL` exists in couple other teal packages. The prefix in dataset names makes it sure you use the dataset from a specific package, if ever `rADSL` is changed in other package and it's different than the one in `teal.transform`. I specifically added the prefix before dataset names https://github.com/insightsengineering/teal.transform/pull/142 We had a conversation in there that this was not crucial, but was clean in case you load multiple packages (teal.transform, then teal.goshawk) and have multiple `rADSL` datasets.

File: README.md [hunk 5]
```diff
@@ -25,7 +25,7 @@ This package contains functions and shiny modules for extracting and merging dat
 
 ```r
 # stable versions
-install.packages('teal.transform', repos = c('https://insightsengineering.r-universe.dev', getOption('repos')))
+install.packages('teal.slice')
```
Comment (kartikeyakirar) [inline README.md:28]:
```suggestion
install.packages('teal.transform')
```

**Comment by averissimo** [comment]
@m7pr thanks. I was not aware of that conversation. It makes total sense

I'll revert the changes. Do you think we should add a comment on the first occurrence to give that context and prevent any future changes to that?

**Comment by m7pr** [comment]
> I'll revert the changes. Do you think we should add a comment on the first occurrence to give that context and prevent any future changes to that?

Yes please. A comment like `using prefix in case similar dataset exist in other package`.

**Comment by m7pr** [comment]
Hey team this is really great effort. I put my 2 cents in the review of vignettes https://github.com/insightsengineering/teal.transform/pull/183

File: tests/testthat/setup-skip_if_too_deep.R [hunk 6]
```diff
@@ -23,26 +24,33 @@ testing_depth <- function() { # nolint # nousage
...
-#' @return \code{NULL} or invoke an error produced by \code{testthat::skip}
-#' @note By default \code{TESTING_DEPTH} is equal to 3 if there is no environment variable for it.
-#' By default \code{depth} argument lower or equal to 3 will not be skipped because by default \code{TESTING_DEPTH}
-#' is equal to 3. To skip <= 3 depth tests then the environment variable has to be lower than 3 respectively.
+#'
+#' @note By default `TESTING_DEPTH` is equal to 3 if there is no environment variable for it.
+#' By default `depth` argument lower or equal to 3 will not be skipped because by default `TESTING_DEPTH`
+#' is equal to 3.
+#' To skip <= 3 depth tests then the environment variable has to be lower than 3 respectively.
 skip_if_too_deep <- function(depth) { # nolintr
```
Comment (pawelru) [inline tests/testthat/setup-skip_if_too_deep.R:54]: It looks like this function is not used at all! Possibly to remove

Comment (averissimo) [reply tests/testthat/setup-skip_if_too_deep.R]: That one is safe to remove! Done in 3ec9d7be

We've found  bunch of others, but I'm a bit reluctant on removing those without a deeper understanding of the package

> ([comment](https://github.com/insightsengineering/teal.transform/pull/176#issuecomment-1935996312)) List of unused functions (WIP):
>
> note: that this doesn't mean they will be deleted! Maybe this should only be done in refactor after release.

> - `call_condition_logical`
> - `call_condition_range_date`
> - `call_condition_range_posixct`
> - `call_extract_array`
> - `get_initial_filter_values`
> - `check_data_extract_spec_react`
> - `extract_choices_labels`

> Functions only used in `@examples`

> - `call_extract_list`
> - `call_condition_range`
> - `call_with_colon`

Comment (pawelru) [reply tests/testthat/setup-skip_if_too_deep.R]: Good call. I would have to also spend some to decide what to do with them. Let's leave them for now. After we done with all the CRAN releases I want to anyway come back here and we might decide then what to do.

File: R/Queue.R [hunk 7]
```diff
@@ -1,8 +1,10 @@
...
-#' @title R6 Class - A First-In-First-Out Abstract Data Type
+#' R6 Class - A First-In-First-Out Abstract Data Type
+#'
+#' @description
+#' `r lifecycle::badge("experimental")`
 #'
-#' @description `r lifecycle::badge("experimental")`\cr
 #' Abstract data type that stores and returns any number of elements.
 #'
 #' A `Queue` object stores all elements in a single vector,
```
Comment (kartikeyakirar) [inline R/Queue.R:10]:
```suggestion
#' @details
#' A `Queue` object stores all elements in a single vector,
```

File: R/Queue.R [hunk 8]
```diff
@@ -1,8 +1,10 @@
 # Queue ====
 
-#' @title R6 Class - A First-In-First-Out Abstract Data Type
```
Comment (kartikeyakirar) [inline R/Queue.R:3]: should we add tags

#' @name Queue
#' @docType class

File: R/Queue.R [hunk 9]
```diff
@@ -19,9 +21,9 @@ Queue <- R6::R6Class( # nolint
     #' @description
     #' Adds element(s) to `Queue`.
     #'
-    #' @param new_elements vector of elements to add
+    #' @param new_elements vector of elements to add.
     #'
-    #' @return self invisibly
+    #' @return Self, invisibly.
```
Comment (kartikeyakirar) [inline R/Queue.R:26]:
```suggestion
    #' @return `self`, invisibly.
```
Can you check this other places as well.

File: R/Queue.R (hunk 8 above)
Comment (averissimo) [reply R/Queue.R:3]: I looked at https://github.com/r-lib/pkgdepends/blob/main/R/pkg-installation.R for reference as they don't use any other tags.

But given that `teal.slice` uses `@doctype`, there's no harm on it. I'll make the change :+1: 

`@name` does nothing, is it worth adding it?

File: R/Queue.R [hunk 10]
```diff
@@ -77,15 +79,15 @@ Queue <- R6::R6Class( # nolint
     #' @description
     #' Returns the number of elements in `Queue`.
     #'
-    #' @return integer of length 1
+    #' @return Integer of length 1.
```
Comment (kartikeyakirar) [inline R/Queue.R:82]:
```suggestion
    #' @return `integer(1)`
```

File: R/Queue.R (hunk 9 above)
Comment (averissimo) [reply R/Queue.R:26]: I'm on the fence on this one as it's not a data type.

I won't push it though, I'll make the change

File: R/Queue.R (hunk 10 above)
Comment (averissimo) [reply R/Queue.R:82]: Made a small edit to your comment to include the full stop.

File: R/Queue.R [hunk 11]
```diff
@@ -77,15 +79,15 @@ Queue <- R6::R6Class( # nolint
...
     size = function() {
       length(self$get())
     },
     #' @description
     #' Prints this `Queue`.
     #'
-    #' @param ... additional arguments to this method, ignored
+    #' @param ... Additional arguments to this method, ignored.
     #'
     #' @return invisibly self
```
Comment (kartikeyakirar) [inline R/Queue.R:93]:
```suggestion
    #' @return `self`, invisibly.
```

File: R/Queue.R (hunk 8 above)
Comment (kartikeyakirar) [reply R/Queue.R:3]: `@name` if does not do anything lets leave it .

File: R/Queue.R (hunk 9 above)
Comment (kartikeyakirar) [reply R/Queue.R:27]: there was discussion on this https://github.com/insightsengineering/teal.slice/pull/506#discussion_r1464750879. in r6 documentation as well its used with backticks

File: R/Queue.R (hunk 11 above)
Comment (averissimo) [reply R/Queue.R]: Done in f20642a3

File: R/all_choices.R [hunk 12]
```diff
@@ -1,9 +1,9 @@
-#' An S3 structure representing the selection of all
-#' possible choices in a `filter_spec`, `select_spec` or `choices_selected` object.
+#' An S3 structure representing the selection of all possible choices in a
```
Comment (kartikeyakirar) [inline R/all_choices.R:1]: this is very long tittle , it should be description.

File: R/Queue.R (hunk 8 above)
Comment (averissimo) [reply R/Queue.R:3]: I assume "Leave it (as is)"

File: R/all_choices.R (hunk 12 above)
Comment (kartikeyakirar) [reply R/all_choices.R:1]: it could be e.g @title Universal selector for specifications

File: R/call_utils.R [hunk 13]
```diff
@@ -1,9 +1,14 @@
 #' Checks `varname` argument and convert to call
 #'
 #' Checks `varname` type and parse if it's a `character`
-#' @param varname (`name`, `call` or `character(1)`)\cr
-#'   name of the variable
+#'
+#' @param varname (`name`, `call` or `character(1)`)
```
Comment (kartikeyakirar) [inline R/call_utils.R:5]:
```suggestion
#' @param varname (`name` or `call` or `character(1)`)
```

File: R/call_utils.R [hunk 14]
```diff
@@ -30,33 +35,37 @@ call_check_parse_varname <- function(varname) {
...
-#'     \item{`factor`}{ call is composed on choices converted to `character`}
-#'     \item{`Date`}{ call is composed on choices converted to `character` using `format(choices)`}
-#'     \item{`POSIXct`, `POSIXlt`}{ Call is composed on choices converted to `character` using
-#'       `format(choices)`. One has to be careful here as formatted date-time variable might loose
-#'       some precision (see `format` argument in \code{\link{format.POSIXlt}}) and output call
-#'       could be insufficient for exact comparison. In this case one should specify
-#'       `varname = trunc(<varname>)` and possibly convert `choices` to `character`)
-#'     }
-#'   }
+#' @param varname (`name`, `call` or `character(1)`)
```
Comment (kartikeyakirar) [inline R/call_utils.R:38]:
```suggestion
#' @param varname (`name` or `call` or `character(1)`)
```

File: R/call_utils.R [hunk 15]
```diff
@@ -223,28 +244,33 @@ call_condition_range_date <- function(varname, range) {
...
-#' @param dataname (`character(1)` or `name`)\cr
-#' @param row (`name`, `call`, `logical`, `integer`, `character`)\cr
-#'   optional, name of the `row` or condition
-#' @param column (`name`, `call`, `logical`, `integer`, `character`)\cr
-#'   optional, name of the `column` or condition
-#' @param aisle (`name`, `call`, `logical`, `integer`, `character`)\cr
-#'   optional, name of the `row` or condition
-#' @return `[` call with all conditions included
+#' @param dataname (`character(1)` or `name`).
+#' @param row (optional `name`, `call`, `logical`, `integer` or `character`)
```
Comment (kartikeyakirar) [inline R/call_utils.R:248]:
```suggestion
#' @param row (optional `name` or `call`, `logical`, `integer` or `character`)
```

Comment (kartikeyakirar) [reply R/call_utils.R:248]: could you please check all the similar instance. we have replaced it in other packages with `or`

File: R/check_selector.R [hunk 16]
```diff
@@ -11,9 +12,9 @@ check_selector_dataname <- function(dataname) {
 
 #' Check selector filters element
 #'
-#' @param filters selector element generated by `data_extract_srv`
+#' @param filters (`list`) selector element generated by `data_extract_srv`.
 #'
-#' @return error or nothing
+#' @return Raises and error when check fails, otherwise it returns `NULL`, invisibly.
```
Comment (kartikeyakirar) [inline R/check_selector.R:17]:
```suggestion
#' @return Raises an error when the check fails, otherwise it returns `NULL`, invisibly.
```

File: R/check_selector.R [hunk 17]
```diff
@@ -76,9 +81,10 @@ check_selector_internal_id <- function(internal_id) {
...
 #'
-#' @param selector (`list`) of selector elements generated by `data_extract_srv`
+#' @param selector (`list`) of selector elements generated by `data_extract_srv`.
 #'
-#' @return error or nothing
+#' @return Raises an error when check fails, otherwise, it returns the `selector`
+#' parameter, invisibly and unchanged.
 #'
 #' @noRd
 check_selector <- function(selector) {
```
[the remark this answers is not in the document]
Comment (kartikeyakirar) [reply R/check_selector.R:90]: It makes more sense to use assert based on the definition of functions, but I'm not sure if it can cause a namespace collision. Could you check that? I'm okay with converting check to assert.

File: R/check_selector.R [hunk 18]
```diff
@@ -1,8 +1,9 @@
 #' Check selector `dataname` element
 #'
-#' @param dataname selector element
+#' @param dataname (`character(1)`) selector element.
 #'
-#' @return error or nothing
+#' @return Raises an error when check fails, otherwise, it returns the `dataname`
+#' parameter, invisibly and unchanged.
 #'
 #' @noRd
```
[the remark this answers is not in the document]
Comment (m7pr) [reply R/check_selector.R:8]: But I think there is a difference for noRd as there is no manual page at all. Where for `@keywords internal` the manual page exists, but is not listed in package INDEX (list that shows when you run `help(package = "package name")`

[the remark this answers is not in the document]
Comment (vedhav) [reply R/check_selector.R:8]: `@kartikeyakirar` casually tagging a random GitHub user 😄

[the remark this answers is not in the document]
Comment (m7pr) [reply R/check_selector.R:8]: hello @nord : D

File: R/choices_labeled.R [hunk 19]
```diff
@@ -1,59 +1,65 @@
-#' Set "`<choice>:<label>`" type of Names
+#' Set "`<choice>:<label>`" type of names
+#'
+#' @description
+#' `r lifecycle::badge("stable")`
 #'
-#' @description `r lifecycle::badge("stable")`
 #' This is often useful for [choices_selected] as it marks up the drop-down boxes
```
Comment (kartikeyakirar) [inline R/choices_labeled.R:6]:
```suggestion
#' This is often useful for [choices_selected()] as it marks up the drop-down boxes
```
should this be?

File: tests/testthat/setup-skip_if_too_deep.R (hunk 6 above)
Comment (m7pr) [reply tests/testthat/setup-skip_if_too_deep.R]: I think you can use `grep` in `bash/shell` to see if this function is used outside of this package. Try running this in a folder where all our packages are apps are included

```r
grep --include=\*.R --recursive '.' -e 'function_name'
```

File: R/check_selector.R (hunk 18 above)
[the remark this answers is not in the document]
Comment (kartikeyakirar) [reply R/check_selector.R:8]: Oh wow, I didn't put backtick! :sweat_smile: :sweat_smile: This could be a really cool new marketing idea 😆

**Comment by m7pr** [comment]
Hey @averissimo can you open an extra issue for detection of not used functions?
I think we can list all functions in the package and check with grep, if they are used in other teal packages or teal.gallery with 

```r
grep --include=\*.R --recursive '.' -e 'function_name'
```

Once we talked about detecting packages that are in Imports but are not used in the package, maybe a snippet created by @pawelru could help you https://github.com/insightsengineering/idr-tasks/issues/632#issuecomment-1708223277 as I think the code you made in your comment is long https://github.com/insightsengineering/teal.transform/pull/176#issuecomment-1935996312

File: R/choices_selected.R [hunk 20]
```diff
@@ -174,25 +183,33 @@ choices_selected <- function(choices,
   )
 }
 
-#' Check if an object is a choices_selected class.
+#' Check if an object is a choices_selected class
 #'
-#' @description `r lifecycle::badge("stable")`
+#' `r lifecycle::badge("stable")`
```
Comment (kartikeyakirar) [inline R/choices_selected.R:188]:
```suggestion
```

in documentation it shows two badges

File: R/choices_selected.R [hunk 21]
```diff
@@ -174,25 +183,33 @@ choices_selected <- function(choices,
   )
 }
 
-#' Check if an object is a choices_selected class.
+#' Check if an object is a choices_selected class
```
Comment (kartikeyakirar) [inline R/choices_selected.R:186]: this can go inside details section of `choices_selected`. Here its not visible anyways

File: R/choices_selected.R [hunk 22]
```diff
@@ -244,8 +261,7 @@ vector_reorder <- function(vec, idx) {
   }
 
   attributes(vec) <- vec_attrs
-
-  return(vec)
+  vec
 }
 
 vector_pop <- function(vec, idx) {
```
Comment (kartikeyakirar) [inline R/choices_selected.R:267]: I think we should explicitly add theses tags before utils function definition 
```suggestion
#' @noRd
#' @keyword internal
vector_pop <- function(vec, idx) {
```

File: R/Queue.R (hunk 9 above)
Comment (averissimo) [reply R/Queue.R]: Done in f20642a3

File: R/all_choices.R (hunk 12 above)
Comment (averissimo) [reply R/all_choices.R:1]: Done in 7a186069

```diff
diff --git a/R/all_choices.R b/R/all_choices.R
index 29a79918..be01f441 100644
--- a/R/all_choices.R
+++ b/R/all_choices.R
@@ -1,8 +1,11 @@
-#' An S3 structure representing the selection of all possible choices in a
-#' `filter_spec`, `select_spec` or `choices_selected` object
+#' Bare constructor for `all_choices` object
 #'
+#' @description
 #' `r lifecycle::badge("experimental")`
 #'
+#' An S3 structure representing the selection of all possible choices in a
+#' `filter_spec`, `select_spec` or `choices_selected` object
+#'
```

File: R/choices_selected.R (hunk 22 above)
Comment (averissimo) [reply R/choices_selected.R:270]: Done in 5887a0b1 I think I caught all

File: R/choices_selected.R (hunk 21 above)
Comment (averissimo) [reply R/choices_selected.R]: How about this: 
image

Done in cfa88ffd

Resolve if it looks fine (uses `@describeIn` tag)

File: _pkgdown.yml [hunk 23]
```diff
@@ -23,7 +23,7 @@ navbar:
 reference:
   - title: Data extract constructors
     desc: >-
-      Functions used to create transform instructions for teal applications.
+      Functions used to create transform instructions for `teal` applications.
```
Comment (kartikeyakirar) [inline _pkgdown.yml:26]: there  is one more occurrence below in section : Data extract modules

File: R/utils.R [hunk 24]
```diff
@@ -157,6 +166,14 @@ compose_and_enable_validators <- function(iv, selector_list, validator_names = N
   iv
 }
 
+#' Ensures datasets is a list of reactive expression
+#'
+#' @param datasets (`reactive` or `teal_data` object or `list`) of `data.frame`
+#' wrapped or not in a reactive expression.
+#'
+#' @return List of reactive expression that contains all the individual `datasets`.
```
Comment (kartikeyakirar) [inline R/utils.R:174]:
```suggestion
#' @return List of `reactive` expression that contains all the individual `datasets`.
```

File: R/utils.R [hunk 25]
```diff
@@ -157,6 +166,14 @@ compose_and_enable_validators <- function(iv, selector_list, validator_names = N
   iv
 }
 
+#' Ensures datasets is a list of reactive expression
+#'
+#' @param datasets (`reactive` or `teal_data` object or `list`) of `data.frame`
```
Comment (kartikeyakirar) [inline R/utils.R:171]: I believe we should consider removing the object following `teal_data` in this and similar instances.

File: R/select_spec.R [hunk 26]
```diff
@@ -189,11 +187,11 @@ select_spec.default <- function(choices, # nolint
...
-  res <- list(
-    choices = choices, selected = selected, multiple = multiple, fixed = fixed,
-    always_selected = always_selected, ordered = ordered, label = label
+  structure(
+    list(
+      choices = choices, selected = selected, multiple = multiple, fixed = fixed,
+      always_selected = always_selected, ordered = ordered, label = label
+    ),
+    class = "select_spec"
   )
```
Comment (kartikeyakirar) [inline R/select_spec.R:196]: looks great 👍

File: R/resolve.R [hunk 27]
```diff
@@ -1,29 +1,35 @@
...
 #'
-#' @description `r lifecycle::badge("stable")`
+#' `r lifecycle::badge("stable")`
 #'
-#' @param x Object of class `delayed_data` to resolve.
-#' @param datasets A named list of type `data.frame` to use for evaluation.
-#' @param keys A named list of type `character` to be used as the keys for each dataset. The names of this
-#'  list must be exactly the same as for datasets.
+#' @note This is an internal function that is used by [resolve_delayed()].
+#' All the methods are used internally only.
```
Comment (kartikeyakirar) [inline R/resolve.R:6]: I think we could removed this. is there a reason to add note for this ?

File: R/utils.R (hunk 24 above)
Comment (averissimo) [reply R/utils.R:174]:
```suggestion
#' @return List of `reactive` expressions that contains all the individual `datasets`.
```

File: R/resolve.R (hunk 27 above)
Comment (averissimo) [reply R/resolve.R:6]: It gives context to why this is not `@export`ed when the methods "are". This is non-standard usage for S3 in a package (at least I haven't seen this before).

I think we should keep it in the meantime (this discussion may say otherwise https://github.com/insightsengineering/coredev-tasks/issues/510)

File: R/check_selector.R (hunk 18 above)
[the remark this answers is not in the document]
Comment (averissimo) [reply R/check_selector.R:8]: Seems fair, as long as there's "complete" documentation, we can change to `@keywords` internal

File: _pkgdown.yml (hunk 23 above)
Comment (averissimo) [reply _pkgdown.yml:26]: :facepalm:

Comment (averissimo) [reply _pkgdown.yml:26]: ce1ab3d0

File: _pkgdown.yml [hunk 28]
```diff
@@ -41,7 +41,7 @@ reference:
       - resolve
       - resolve_delayed
   - title: Data extract modules
-    desc: teal modules to generate transform expressions
+    desc: `teal` modules to generate transform expressions
```
Comment (vedhav) [inline _pkgdown.yml:44]:
```suggestion
    desc: teal modules to generate transform expressions
```

pkgdown is complaining when we start the title with "`"

File: R/utils.R (hunk 25 above)
Comment (averissimo) [reply R/utils.R:171]: Why? The function still supports it. So I think we should keep it, unless we change the code.

File: _pkgdown.yml (hunk 28 above)
Comment (kartikeyakirar) [reply _pkgdown.yml:44]: we could put the entire sentence in doub quote

 "`teal` modules to generate transform expressions"

Comment (averissimo) [reply _pkgdown.yml]: It's fixed now. I'm taking a look at the CI errors :-)

**Comment by averissimo** [comment]
> Hey @averissimo can you open an extra issue for detection of not used functions? I think we can list all functions in the package and check with grep, if they are used in other teal packages or teal.gallery with
> 
> ```r
> grep --include=\*.R --recursive '.' -e 'function_name'
> ```

Created this one: https://github.com/insightsengineering/teal.transform/issues/196

Btw, the script uses `grep` via system call and then {crayon} to enhance the readability :-)

File: R/utils.R (hunk 25 above)
Comment (kartikeyakirar) [reply R/utils.R:171]: sorry, I phrased it wrong. What I meant to say was that the keyword `object ` unnesseray  at the end of `teal_data`

Comment (averissimo) [reply R/utils.R:171]:
```suggestion
#' @param datasets (`reactive` or `teal_data` or `list`) of `data.frame`
```

File: R/check_selector.R (hunk 18 above)
[the remark this answers is not in the document]
Comment (averissimo) [reply R/check_selector.R:8]:
```suggestion
#' @keywords internal
```

File: R/check_selector.R (hunk 17 above)
[the remark this answers is not in the document]
Comment (averissimo) [reply R/check_selector.R:90]: To be done in a different PR

**Review by kartikeyakirar — APPROVED** [review]
@averissimo  Looks good to me! I believe it's ready to merge.
