### PR TITLE
remove chunks + merge_expression_srv

### LINKED ISSUE #61: data_merge - remove dependency on FilteredData and chunks.
Remove dependency of data_merge on FilteredData and chunks. To avoid crash of all apps please create a new module which fulfils following requrements: 

- merge module should return merge expression which then should be executed outside. We shouldn't create a chunks object which then needs to be pushed to chunks.
- merge module should not depend on the datasets. [join_keys](https://github.com/insightsengineering/teal.transform/blob/736c7c96d1416b5fd49e49ebad324a0e6e976f99/R/merge_datasets.R#L55) can be passed as a join_keys argument, and [data](https://github.com/insightsengineering/teal.transform/blob/736c7c96d1416b5fd49e49ebad324a0e6e976f99/R/merge_datasets.R#L89) can be passed as a list of reactive (or not) data.frames. Research if the data is needed there - if the code will be evaluated outside then data should not be needed.
- deprecate old modules

### PR DESCRIPTION
**Pull request by mhallal1**
closes #61 
replaces https://github.com/insightsengineering/teal.transform/pull/75 to have the same branch name as https://github.com/insightsengineering/teal/pull/674

Dependency on `datasets` and `chunks` has been removed from data merge module is such a way:
1) New modules `merge_expression_module` and `merge_expression_srv` which are the new versions of `data_merge_module` and `data_merge_srv`. The new modules have  an additional argument `join_keys` and the argument `datasets` accepts a list of reactive or non-reactive data.frames. So we have a separation between the old modules that accept `FilteredData` and the new modules that accept a named list of reactive/non-reactive data.frames.
2) `Merge_datasets` is modified to use a list of reactive data.frames instead of `FilteredData` and chunks was completely removed from it. It now returns a list of `expr`, `columns_source`, `key` and `filter_info`. No `data` or `chunks` are returned anymore. Be aware that `expr` now is a list of calls instead of character.
3) `get_dplyr_call` and `get_merge_call` have been modified accordingly.
4) `data_merge_srv` has been modified in a way to use the same `merge_datasets`, `get_dplyr_call` and `get_merge_call` scripts. It defines `data` and `join_keys` internally and calls `merge_expression_srv` where it appends `data` and `chunks` to the returned list.
5) `join_keys` argument replaces `keys` argument of `data_extract_XXX`. This is to avoid the confusion of having to use `join_keys`(data_merge_XXX) and `keys` (data_extract_XXX) in the same module. We extract internally the keys corresponding to every dataset from the `join_keys` input.
6) Tests are added and modified as needed.

Please test with the example apps in `merge_expression_module.R` and `data_merge_module.R`. 

The design of the apps would be like this now:
```
server = function(input, output, session) {
#initialize chunks
chunks_h <- teal.code::chunks_new()

#push data in chunks

#call data_merge
merged_data <- merge_expression_srv(
      selector_list = selector_list,
      datasets = data_list,
      join_keys = join_keys,
      merge_function = "dplyr::left_join"
    )

#push data_merge code in chunks
ch_merge <- reactive({ 
      ch <- teal.code::chunks_deep_clone(chunks_h)
      for (chunk in merged_data()$expr) teal.code::chunks_push(chunks = ch, expression = chunk)
      ch$eval()
      ch
    })

#get output from chunks

}

### CODE REVIEW

File: R/data_merge_module.R [hunk 1]
```diff
@@ -230,6 +226,11 @@ data_merge_srv <- function(id = "merge_id",
                            datasets,
                            merge_function = "dplyr::full_join",
                            anl_name = "ANL") {
+  lifecycle::deprecate_soft(
+    when = "0.1.2",
+    what = "data_merge_srv()",
+    details = "Please use `merge_expression_srv()` instead."
+  )
```
Comment (gogonzo) [inline R/data_merge_module.R:233]: Let's deprecate at the end of increment when we implement the new merge to the tm modules. Otherwise all our modules will throw warning.

File: R/merge_expression_module.R [hunk 2]
```diff
@@ -0,0 +1,352 @@
...
+#'
+#' join_keys <- list(
+#'   ADSL = list(
+#'     ADSL = c(STUDYID = "STUDYID", USUBJID = "USUBJID"),
+#'     ADLB = c(STUDYID = "STUDYID", USUBJID = "USUBJID")
+#'   ),
+#'   ADLB = list(
+#'     ADLB = c(STUDYID = "STUDYID", USUBJID = "USUBJID", PARAMCD = "PARAMCD", AVISIT = "AVISIT"),
+#'     ADSL = c(STUDYID = "STUDYID", USUBJID = "USUBJID")
+#'   )
```
Comment (nikolas-burkoff) [inline R/merge_expression_module.R:224]: So this issue https://github.com/insightsengineering/teal.slice/issues/53 is really important I think, we're going to end up creating duplication i.e. helper functions for creating join_keys embedded inside teal.data::cdisc_data, the same inside teal.slice and then also here.

File: tests/testthat/test-merge_expression_srv.R [hunk 3]
```diff
@@ -0,0 +1,293 @@
...
+    args = list(selector_list = selector_list, datasets = data_list, join_keys = join_keys),
+    expr = {
+      testthat::expect_true(inherits(session$returned()$expr, "list"))
+      testthat::expect_true(inherits(session$returned()$expr[[1]], "<-"))
+      testthat::expect_identical(
+        c(
+          "ADSL_FILTERED <- ADSL",
+          "ADLB_FILTERED <- ADLB",
+          "ANL_1 <- ADSL_FILTERED %>% dplyr::select(STUDYID, USUBJID, AGE)",
+          "ANL_2 <- ADLB_FILTERED %>% dplyr::select(STUDYID, USUBJID, AVAL, CHG)",
```
Comment (nikolas-burkoff) [inline tests/testthat/test-merge_expression_srv.R:231]: So in the longer term - should the merge expression actually contain the filter call - I guess the advantage is it contains everything needed to recreate the data at this point, the disadvantage is that if you have multiple data merges in the same module you'll end up with multiple expressions of the filtering and this could get very confusing/wrong if we are removing "_FILTERED" etc. as the datasets coming into a module may or may not have been filtered

So I wonder if the module developer should be in charge of what to do with the "pure" merge expression and if they wish to append it to some chunk which contains the filtered data expression then they can - and maybe for a second merge they wish to do something different

The dplyr::select stuff lives with the data_extract_spec doesn't it -> so you could imagine the merge call not actually returning them either (and the d-e-s doing so further decoupling things) - but I suspect that would be harder

**Review by nikolas-burkoff — COMMENTED** [review]
A few comments from me in-line - mostly for work after this PR

File: R/data_extract_module.R [hunk 4]
```diff
@@ -429,6 +428,12 @@ data_extract_srv.list <- function(id, datasets, data_extract_spec, keys = NULL,
         "data_extract_srv.list initialized with datasets: { paste(names(datasets), collapse = ', ') }."
       )
 
+      # get keys out of join_keys
+      is_nested_list <- any(sapply(join_keys, is.list))
```
[the remark this answers is not in the document]
Comment (nikolas-burkoff) [reply R/data_extract_module.R:432]: I guess this comes back to how we are splitting things up. Users need to specify the keys for merging/joining data.frames together, we then need to use this information throughout the code base and we probably need helper functions to create this information in a simpler way for standard cases such as cdisc.

This suggests we need a (possibly very lightweight) object to standardize creation and usage. At the moment we have both JoinKeys and a named nested list, which I think is confusing for everyone - for users as there are two distinct ways for creating the information (tbh both about as equally complex) and for us  - as there are two different ways for accessing the information. Should we use JoinKeys throughout? Or should we abandon them everywhere in favour of a nested list and manually extract what's needed each time from it.

This sort of comment probably applies to other things as well - you can create a TealDataset or just create a data.frame with some attributes etc.

File: R/data_merge_module.R (hunk 1 above)
Comment (mhallal1) [reply R/data_merge_module.R]: removed.

File: R/data_extract_module.R (hunk 4 above)
[the remark this answers is not in the document]
Comment (mhallal1) [reply R/data_extract_module.R]: I have just simplified this step, there is no more check for a nested list. We can accept a nested join_keys list format only.

File: R/data_extract_module.R [hunk 5]
```diff
@@ -395,31 +395,30 @@ data_extract_srv.FilteredData <- function(id, datasets, data_extract_spec, ...)
         reactive(datasets$get_data(dataname = x, filtered = TRUE))
       })
 
-      key_list <- sapply(X = datasets$datanames(), simplify = FALSE, FUN = function(x) {
-        datasets$get_keys(dataname = x)
-      })
+      join_keys_list <- datasets$get_join_keys()
```
[the remark this answers is not in the document]
Comment (mhallal1) [reply R/data_extract_module.R:398]: Issue create in `teal.slice` as discussed:
https://github.com/insightsengineering/teal.slice/issues/58

File: R/data_extract_module.R (hunk 4 above)
[the remark this answers is not in the document]
Comment (gogonzo) [reply R/data_extract_module.R]: Yes, I have created an issue in TealData to simplify the JoinKeys and to make wrappers which can ease up the creation of the join_keys list. 

https://github.com/insightsengineering/teal.data/issues/78

File: tests/testthat/test-merge_expression_srv.R (hunk 3 above)
Comment (gogonzo) [reply tests/testthat/test-merge_expression_srv.R:231]: @nikolas-burkoff we need to continue discussion about filtering in data_extract_spec/data_merge and find the solution for this. I made a [comment in my PR](https://github.com/insightsengineering/teal/pull/674#issue-1281938088) which adds more into this equation. 

I think it is nuts that we need to depend on hardcoded _FILTERED in data_merge_expr but we have no alternative at this moment. We should rather keep the same name as in the reactive list (environment should be consisten with the code).

Let's re-initialize discussions about data_merge soon

Comment (nikolas-burkoff) [reply tests/testthat/test-merge_expression_srv.R:231]: yup, this was definitely not to be addressed in this PR...

File: R/data_merge_module.R [hunk 6]
```diff
@@ -86,7 +86,7 @@
 #'       datasets = datasets,
 #'       merge_function = "dplyr::left_join"
 #'     )
-#'     output$expr <- renderText(merged_data()$expr)
+#'     output$expr <- renderText(paste(merged_data()$expr, collapse = "\n"))
```
Comment (gogonzo) [inline R/data_merge_module.R:89]: In data_merge_srv there is `merged_data$expr <- paste(merged_data$expr, collapse = "\n")`. SO paste is not needed


```suggestion
#'     output$expr <- renderText(merged_data()$expr)
```

**Review by gogonzo — APPROVED** [review]
Everything works with https://github.com/insightsengineering/teal/pull/674
Former tests return the same output 👍 
Please add the NEWS entry

File: NEWS.md [hunk 7]
```diff
@@ -3,6 +3,7 @@
 ### New features
 
 * `data_extract_ui`, `data_extract_srv`, `data_extract_multiple_srv` can be initialized by the list of (optionally `reactive`) `data.frame` objects.
+* Added new modules `merge_expression_srv` and `merge_expression_module`, updates of `data_merge_srv` and `data_merge_module` respectively, where `datasets` argument takes a list of (optionally `reactive`) `data.frame` objects and a new argument `join_keys`.
```
Comment (nikolas-burkoff) [inline NEWS.md:6]: I would add that in a later version we will be deprecating the old ones?

File: R/data_extract_module.R [hunk 8]
```diff
@@ -395,31 +395,30 @@ data_extract_srv.FilteredData <- function(id, datasets, data_extract_spec, ...)
...
+        join_keys = join_keys_list
       )
       filter_and_select_reactive
     }
   )
 }
 
 #' @rdname data_extract_srv
-#' @param keys (`list`) of keys per dataset in `datasets`
+#' @param join_keys (named `list`) of keys per dataset in `datasets`
```
Comment (nikolas-burkoff) [inline R/data_extract_module.R:412]: or NULL

File: R/data_extract_module.R [hunk 9]
```diff
@@ -589,29 +592,23 @@ data_extract_multiple_srv.FilteredData <- function(data_extract, datasets, ...)
...
-    datasets$get_keys(dataname = x)
-  })
-  data_extract_multiple_srv(data_extract = data_extract, datasets = data_list, keys = key_list)
+  join_keys_list <- datasets$get_join_keys()
+  data_extract_multiple_srv(data_extract = data_extract, datasets = data_list, join_keys = join_keys_list)
 }
 
 #' @rdname data_extract_multiple_srv
-#' @param keys (`list`) of keys per dataset in `datasets`
+#' @param join_keys (named `list`) of join keys per dataset in `datasets`.
```
Comment (nikolas-burkoff) [inline R/data_extract_module.R:600]: or NULL

File: R/data_merge_module.R [hunk 10]
```diff
@@ -243,16 +234,40 @@ data_merge_srv <- function(id = "merge_id",
...
+          datasets = datasets_list,
+          join_keys = join_keys,
           merge_function = merge_fun_name,
           anl_name = anl_name
         )
+        ch <- teal.code::chunks_new()
+        datasets_list_nr <- sapply(
+          datasets$datanames(),
+          simplify = FALSE,
+          function(x) datasets$get_data(x, filtered = TRUE)
```
Comment (nikolas-burkoff) [inline R/data_merge_module.R:259]: I don't think you can do the nicer 

sapply(datasets$datanames(), simplify = FALSE, datasets$get_data, filtered = TRUE)

File: R/data_merge_module.R [hunk 11]
```diff
@@ -243,16 +234,40 @@ data_merge_srv <- function(id = "merge_id",
...
+        )
+        teal.code::chunks_reset(envir = list2env(datasets_list_nr), chunks = ch)
+        for (chunk in merged_data$expr) teal.code::chunks_push(expression = chunk, chunks = ch)
+        teal.code::chunks_safe_eval(chunks = ch)
+
+        merged_data$data <- reactive({
+          ch$get("ANL")
```
Comment (nikolas-burkoff) [inline R/data_merge_module.R:266]: How does this work with anl_name argument - if that's not ANL?

**Review by nikolas-burkoff — COMMENTED** [review]
A few comments - the ANL one is probably the key one

File: R/data_merge_module.R (hunk 11 above)
Comment (mhallal1) [reply R/data_merge_module.R:266]: good spot, update to take the value of `anl_name`: `ch$get(anl_name)`

File: R/data_extract_module.R (hunk 9 above)
Comment (mhallal1) [reply R/data_extract_module.R:600]: updated.

File: R/data_extract_module.R (hunk 8 above)
Comment (mhallal1) [reply R/data_extract_module.R:412]: updated.

File: NEWS.md (hunk 7 above)
Comment (mhallal1) [reply NEWS.md:6]: added.
